#baseURL = "https://gokarna-hugo.netlify.app"
title = "Rodrigo Müller"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Created with proud by Karoline Rodrigues Firmino"
  #description = "Fundador e maestro da Orquestra Sinfônica de Limeira (OSLI) há 26 anos"
  avatarURL = "/images/maestro.jpg"
  avatarSize = "size-l"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.css" integrity="sha384-6LkG2wmY8FK9E0vU9OOr8UvLwsaqUg9SETfpq4uTCN1agNe8HRdE9ABlk+fVx6gZ" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.js" integrity="sha384-31El76TwmbHj4rF9DyLsygbq6xoIobG0W+jqXim+a3dU9W53tdH3A/ngRPxOzzaB" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>
    
  """
  socialIcons = [

    {name = "facebook", url = "https://www.facebook.com/maestrorodrigomuller"},
    {name = "instagram", url = "https://www.instagram.com/maestrorodrigomuller/"},
    {name = "youtube", url = "https://www.youtube.com/channel/UCcwv_k1WY8GGrukpoX97kzg"},
    #{name = "twitter", url = "https://example.com"},
    #{name = "linkedin", url = "https://example.com"},
    {name = "gmail", url = "mailto:rmoboe@gmail.com"},
  ]
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]

   [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

   [[menu.main]]
    name = "Sobre"
    url = "/sobre/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  #[[menu.main]]
  #  name = "Arranjos"
  #  url = "/arranjos/"
  #  weight = 3

  [[menu.main]]
    name = "Aulas"
    url = "/aulas/"
    weight = 4

  [[menu.main]]
    name = "Lutheria"
    url = "/lutheria/"
    weight = 5

  [[menu.main]]
    name = "Osli"
    url = "/osli/"
    weight = 6

# link whatsapp: https://contate.me/rodrigomuller
  [[menu.main]]
    identifier = "whatsapp"
    pre = "<span data-feather='message-circle'></span>"
    #pre = "<i class='fa-brands fa-whatsapp'></i>"
    url = "https://contate.me/rodrigomuller"
    weight = 7

  #[[menu.main]]
    #identifier = "github"
    #pre = "<span data-feather='github'></span>"
    #url = "https://github.com/karolinefirmino"
    #weight = 8

  #[[menu.main]]
    #identifier = "email"
    #pre = "<span data-feather='mail'></span>"
    #url = "/contato/"
    #weight = 9
